stages:
  - test
  - build

variables:
  CI_REPO: matt.lab/playground/server
  TAG: latest

unit_test:
  stage: test
  image: node:18-alpine
  script:
    - cd server
    - npm ci
    - export JWT_KEY="$JWT_KEY" # 使用環境變數
    - npm run test
  variables:
    JWT_KEY: $JWT_KEY # 確保變數在這裡可用

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_USERNAME: $DOCKER_USERNAME
    DOCKER_PASSWORD: $DOCKER_PASSWORD
    ENV_FILE: $ENV_FILE
  before_script:
    - cd server
    - echo "$ENV_FILE" > .env
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $CI_REGISTRY/$CI_REPO:$TAG .
    - docker push $CI_REGISTRY/$CI_REPO:$TAG
  after_script:
    - cd server
    - rm .env